baseURL = 'https://phalpha.github.io'
languageCode = 'en-us'
title = 'peace, truth, love, joy'
theme = 'harmony'

# Theme parameters
[params]
  subtitle = "A public space for sharing my personal reflections!"
  introTitle = "Welcome to my website!"
  introSubtitle = "My (government) name is Poojit Hegde, and I am an aspiring engineer, scientist, and artist. This is a warm and creative corner of the internet where I share my journey, projects, and thoughts on topics that matter to me."
  showFullHomepage = false  # Set to false for minimal homepage
 # showAbout = true
  #showProjects = true
  #showGallery = true
  #showBlog = true

# Menu configuration
[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"  # Changed from /#about
    weight = 1
  
  [[menu.main]]
    name = "Projects"
    url = "/projects/"  # Changed from /#projects
    weight = 2
  
  [[menu.main]]
    name = "Gallery"
    url = "/gallery/"  # Changed from /#gallery
    weight = 3
  
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 4

# Output formats for RSS
[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "index"
    isPlainText = false

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

[taxonomies]
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Allows raw HTML if needed
      
  [markup.highlight]
    style = "github"
    lineNos = true
    lineNumbersInTable = false
    noClasses = false



