baseURL = 'https://<your-username>.github.io/'
publishDir = 'public'
languageCode = 'en-us'
title = 'Your Name'
theme = 'terminal'

[taxonomies]
  category = 'categories'
  tag = 'tags'

[params]
  themeColor = 'orange'
  backgroundColor = 'light'
  dateFormat = 'January 2, 2006'

[menu]
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/'
    weight = 1
  [[menu.main]]
    identifier = 'projects'
    name = 'Projects'
    url = '/projects'
    weight = 2
  [[menu.main]]
    identifier = 'gallery'
    name = 'Gallery'
    url = '/gallery'
    weight = 3
  [[menu.main]]
    identifier = 'blog'
    name = 'Blog'
    url = '/blog'
    weight = 4
theme = 'terminal'
