baseURL = 'https://phalpha.github.io'
languageCode = 'en-us'
title = 'me, you, and the universe'
theme = 'harmony'

# Theme parameters
[params]
  subtitle = "introspections and extrospections, meditations and expositions"
  introTitle = "Welcome to my website!"
  introSubtitle = "My name is Poojit, and I am an aspiring scientist, artist, and engineer."
  introSubtitle2 = "This is a place where I hope to connect my 'digital personal' to the 'digital public' - a warm and creative corner of the internet where I share stories from my life journey, projects I have worked on, and thoughts on topics that matter to me. Check out the 'About' section to learn a little bit more about who I am, check out the 'Blog' page to read more long-form articles, and check out the 'Thoughts' page for some words I am moving with right now."
  coverImage = "images/blog1_im1.jpg"
  showFullHomepage = false  # Set to false for minimal homepage
 # showAbout = true
  #showProjects = true
  #showGallery = true
  #showBlog = true
  #showThoughts = true
  math = true

# Menu configuration
[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"  # Changed from /#about
    weight = 1
  
  [[menu.main]]
    name = "Projects"
    url = "/projects/"  # Changed from /#projects
    weight = 2
  
  
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3

 [[menu.main]]
    name = "Thoughts"
    url = "/thoughts/"
    weight = 4

# Output formats for RSS
[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "index"
    isPlainText = false

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

[taxonomies]
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Allows raw HTML if needed
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
      
  [markup.highlight]
    style = "github"
    lineNos = true
    lineNumbersInTable = false
    noClasses = false


    





